# -*- coding: utf-8 -*-
from . import faff_job_type
from . import faff_default_task
from . import faff_job
from . import faff_visit
from . import faff_estimate
from . import faff_material
from . import faff_testing
from . import faff_completion
from . import faff_stage_history
from . import crm_lead
from . import sale_order
from . import project
from . import purchase_order
from . import stock_picking
from . import account_move
from . import faff_sample_loader
from . import faff_dashboard
from . import faff_mis_report
