# -*- coding: utf-8 -*-
# Apps screen module icon: Odoo only loads static/description/icon.png (not cafm_icon.png).
# After adding or replacing that file: Apps > Update Apps List (developer mode).
{
    'name': 'CPABooks CAFM',
    'version': '14.0.1.1.160',
    'summary': 'CAFM, AMC, PPM, projects, units, and facility service calls',
    'sequence': -100,
    'description': """CPABooks CAFM for UAE facilities management operations.""",
    'category': 'Services/Facility Management',
    'website': 'https://www.parimaldbz.com',
    'license': 'LGPL-3',
    'images': ['static/description/icon.png'],
    'depends': [
        'maintenance',
        'project',
        'mail',
        'account',
        'sale',
        'base_setup',
        'cpabooks_sequences',
        'professional_templates_v1',
    ],
    'data': [
        'security/cafm_security.xml',
        'security/ir.model.access.csv',
        'data/menu.xml',
        'data/sequence.xml',
        'data/cafm_master_data.xml',
        'data/maintenance_request_sequence.xml',
        'data/cafm_amc_followup_users.xml',
        'data/cafm_invoice_track_status_data.xml',
        'views/cafm_backend_assets.xml',
        'views/cafm_dashboard_views.xml',
        'views/cafm_guide_views.xml',
        'views/cafm_project_views.xml',
        'views/cafm_unit_views.xml',
        'views/amc_register_views.xml',
        'views/cafm_monthly_billing_views.xml',
        'views/cafm_contract_order_views.xml',
        'views/contract_order_monitor_views.xml',
        'views/cafm_pending_cont_order_wizard_views.xml',
        'views/cafm_pending_invoice_wizard_views.xml',
        'views/cafm_amc_invoice_views.xml',
        'views/amc_register_import_views.xml',
        'views/cafm_var_work_import_views.xml',
        'views/cafm_master_views.xml',
        'views/ppm_schedule_views.xml',
        'views/ppm_slot_views.xml',
        'views/ppm_extended_views.xml',
        'views/ppm_wizards_views.xml',
        'views/ppm_menus.xml',
        'views/cafm_sample_loader_views.xml',
        'views/maintenance_request.xml',
        'views/cafm_call_master_views.xml',
        'views/res_users_views.xml',
        'views/cafm_amc_call_views.xml',
        'views/cafm_var_work_views.xml',
        'views/cafm_amc_invoice_reg_views.xml',
        'views/cafm_amc_invoice_import_views.xml',
        'views/cafm_stock_issue_views.xml',
        'views/cafm_mis_report_views.xml',
        'views/cafm_var_print_wizard_views.xml',
        'views/cafm_amc_invoice_print_wizard_views.xml',
        'views/cafm_client_soa_views.xml',
        'views/cafm_amc_next_invoice_print_wizard_views.xml',
        'views/cafm_settings_views.xml',
        'views/cafm_tally_menus.xml',
        'views/maintenance_tenant_views.xml',
        'data/cafm_call_sequences.xml',
        'data/cafm_call_master_data.xml',
        'report/cafm_contract_templates.xml',
        'report/cafm_contract_report.xml',
        'report/cafm_next_invoice_list_report.xml',
        'report/cafm_contract_order_templates.xml',
        'report/cafm_contract_order_report.xml',
        'report/cafm_ppm_daily_report.xml',
        'report/cafm_invoice_tally_report.xml',
    ],
    'demo': [],
    'qweb': [
        'static/src/xml/cafm_dashboard_main.xml',
        'static/src/xml/cafm_guide.xml',
        'static/src/xml/cafm_amc_x_view.xml',
        'static/src/xml/cafm_amc_invoice_status_view.xml',
    ],
    'external_dependencies': {
        'python': ['openpyxl'],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
