# -*- coding: utf-8 -*-
{
    'name': 'Switchgear Manufacturing',
    'summary': 'Switchgear and panel manufacturing in one 16-step cycle: enquiry, estimate, '
               'quotation, design documents, BOM, MO, QC, purchase, GRN, delivery, invoice and payment',
    'description': """
Switchgear
==================
Run switchgear and electrical panel jobs from CRM enquiry to vendor payment:
processing cycle screen, progress status checklist, design document register,
estimate to BOM to MO, QC final inspection tag, dashboard, tutorial wizard and demo data.
""",
    'category': 'Manufacturing',
    'version': '14.0.1.0.0',
    'author': 'Saaskul',
    'website': 'https://saaskul.com',
    'support': 'info.cpabooks@gmail.com',
    'depends': [
        'web', 'mail', 'utm',
        'crm', 'sale_management', 'sale_stock', 'sale_crm', 'sale_project',
        'mrp', 'stock_account', 'purchase_stock', 'account',
        'project', 'hr', 'hr_timesheet',
    ],
    'data': [
        'security/menu_groups.xml',
        'security/ir.model.access.csv',
        'security/switchgear_security.xml',
        'wizard/create_purchase_order.xml',
        'views/switchgear_demo_wizard_views.xml',
        'data/ir_sequence_data.xml',
        'data/flowchart_kanban_data.xml',
        'data/switchgear_quality_data.xml',
        'views/crm_lead_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_bom_views.xml',
        'views/job_estimate_views.xml',
        'views/sale_order_views.xml',
        'views/switchgear_design_document_views.xml',
        'views/stock_picking_views.xml',
        'views/purchase_order_views.xml',
        'views/quality_views.xml',
        'views/purchase_requisition_views.xml',
        'views/account_move_views.xml',
        'views/project_views.xml',
        'views/flowchart_views.xml',
        # Tutorial menuitem parents menu_flowchart_kanban_root (created above).
        'views/switchgear_tutorial_wizard_views.xml',
        'views/menu_groups.xml',
        'views/switchgear_menu_icon.xml',
        'views/switchgear_project_menus.xml',
        'views/switchgear_configuration_action.xml',
        'views/switchgear_configuration_menu.xml',
        'views/switchgear_activity_menus.xml',
        'views/switchgear_odooapp_demo_menu.xml',
        'views/switchgear_hide_top_menus.xml',
        'views/cpabooks_progress_status_views.xml',
        'views/switchgear_assets.xml',
        'report/mrp_report_bom_structure.xml',
        'report/mrp_production_templates.xml',
        'report/qc_label_templates.xml',
        'report/report_menu.xml',
    ],
    'qweb': [
        'static/src/xml/switchgear_dashboard.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'license': 'OPL-1',
}
