from . import cafm_process_steps
from . import cafm_amc_wizard
from . import account_move
from . import cafm_invoice_track
from . import cafm_invoice_tally
from . import amc_register
from . import base_import
from . import cafm_monthly_billing_wizard
from . import cafm_invoice_stagger
from . import cafm_contract_order
from . import cafm_contract_order_report
from . import contract_order_generate
from . import contract_pending_order_wizard
from . import contract_pending_invoice_wizard
from . import contract_order_monitor
from . import cafm_contract_document
from . import cafm_flat_detail
from . import cafm_masters
from . import cafm_amc_call
from . import cafm_var_work
from . import cafm_var_work_remark
from . import cafm_amc_invoice_reg
from . import cafm_amc_invoice_import
from . import cafm_amc_invoice_print_wizard
from . import cafm_stock_issue
from . import cafm_settings
from . import ir_sequence
from . import amc_register_import
from . import cafm_var_work_import
from . import cafm_dashboard
from . import cafm_project
from . import cafm_sample_loader
from . import cafm_unit
from . import crm_gcl
from . import maintenance_request
from . import maintenance_tenant
from . import ppm_schedule
from . import ppm_slot
from . import ppm_wizards
from . import ppm_report
from . import res_users
from . import cafm_var_print_wizard
from . import cafm_client_soa
from . import cafm_amc_register_print

